# appveyor file

version: 0.1.{build}

cache:
  - electron/node_modules
  - '%USERPROFILE%\.electron'
  - electron/elm-stuff

environment:
  matrix:
    - node_version: "7"
      PYTHON: "C:\\Python35"

install:
  - ps: Install-Product node $env:node_version
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - node --version
  - yarn --version
  - python --version

  # Install build tools
  # node
  - cd ./electron
  - yarn install

  # Python
  - cd ../search
  - pip install -r requirements.txt
  - cd ..

test_script:

branches:
  only:
    - master

build_script:
  - cd ./build/win
  - build.bat

  - cd ../electron
  - yarn run build

artifacts:
  - path: electron\dist
    name: Mirusan

build: on
deploy: off
