# appveyor file

version: 0.1.{build}

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

environment:
  matrix:
    - node_version: "7"

install:
  - ps: Install-Product node $env:node_version
  - node --version
  - yarn install
  - yarn --version

  # Install build tools
  - cd ./electron
  - yarn install

test_script:

branches:
  only:
    - master

build_script:
  - yarn run build

artifacts:
  - path: electron\dist
    name: dist

build: on
deploy: off
