# appveyor file

version: 0.1.{build}

cache:
  - electron/node_modules
  - '%USERPROFILE%\.electron'

environment:
  matrix:
    - node_version: "7"

install:
  - ps: Install-Product node $env:node_version
  - node --version
  - yarn --version

  # Install build tools
  - cd ./electron
  - yarn install
  - cd ../search
  - pip install -r requirements.txt
  - cd ..

test_script:

branches:
  only:
    - master

build_script:
  - cd ./electron
  - yarn run build
  - cd ../build/win
  - build.bat


artifacts:
  - path: electron\dist
    name: Mirusan

build: on
deploy: off
